//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_MVC.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApplication_MVC.Resources.ErrorMessage", typeof(ErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current value: {0}.
        /// </summary>
        public static string DatabaseCurrentValue {
            get {
                return ResourceManager.GetString("DatabaseCurrentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data was changed by another user after you loaded this page. Check out the new database values and choose delete again if delete is still the desired action. Changes might also have occured in fields that aren&apos;t displayed. When in doubt return to the main page first..
        /// </summary>
        public static string DatabaseDeleteConcurrencyError {
            get {
                return ResourceManager.GetString("DatabaseDeleteConcurrencyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save data. Try again, and if the problem persists contact your system administrator..
        /// </summary>
        public static string DatabaseSaveError {
            get {
                return ResourceManager.GetString("DatabaseSaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data was changed by another user after you loaded this page. Check out the diffence(s) with the current database values and choose save again to store the changes. Changes might also have occured in fields that aren&apos;t displayed. When in doubt return to the main page first..
        /// </summary>
        public static string DatabaseUpdateConcurrencyError {
            get {
                return ResourceManager.GetString("DatabaseUpdateConcurrencyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data was deleted by another user. Refresh data and try again..
        /// </summary>
        public static string DatabaseUpdateDeletedError {
            get {
                return ResourceManager.GetString("DatabaseUpdateDeletedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has a maximum of {1} characters..
        /// </summary>
        public static string FieldMaxLength {
            get {
                return ResourceManager.GetString("FieldMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be between {2} and {1} characters long..
        /// </summary>
        public static string FieldMinMaxLength {
            get {
                return ResourceManager.GetString("FieldMinMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description has a maximum of 80 characters..
        /// </summary>
        public static string FieldOfInterestDescriptionMaxLength {
            get {
                return ResourceManager.GetString("FieldOfInterestDescriptionMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field of interest.
        /// </summary>
        public static string FieldOfInterestId {
            get {
                return ResourceManager.GetString("FieldOfInterestId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field of interest &quot;{0}&quot; already exists..
        /// </summary>
        public static string FieldOfInterestIdExists {
            get {
                return ResourceManager.GetString("FieldOfInterestIdExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field of interest has a maximum of 5 characters..
        /// </summary>
        public static string FieldOfInterestIdMaxLength {
            get {
                return ResourceManager.GetString("FieldOfInterestIdMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing id parameter to specify the field of interest to display..
        /// </summary>
        public static string FieldOfInterestIdNull {
            get {
                return ResourceManager.GetString("FieldOfInterestIdNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field of interest mandatory..
        /// </summary>
        public static string FieldOfInterestIdRequired {
            get {
                return ResourceManager.GetString("FieldOfInterestIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} mandatory..
        /// </summary>
        public static string FieldRequired {
            get {
                return ResourceManager.GetString("FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing or corrupted id parameter to specify the {0} to update..
        /// </summary>
        public static string RecordIdError {
            get {
                return ResourceManager.GetString("RecordIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} &quot;{1}&quot; unknown / no longer available..
        /// </summary>
        public static string RecordUnknown {
            get {
                return ResourceManager.GetString("RecordUnknown", resourceCulture);
            }
        }
    }
}
